# Generated by Django 6.1.1 on 2026-09-27 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='college_university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
