# Generated by Django 6.1.1 on 2026-09-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidateprofile_age_candidateprofile_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='availability',
            field=models.CharField(blank=True, default='Immediate', max_length=100),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cgpa',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='course',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='graduation_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='other_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_mode',
            field=models.CharField(blank=True, default='remote', max_length=30),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='projects',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='semester_year',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='technical_skills',
            field=models.TextField(blank=True),
        ),
    ]
