# Generated by Django 6.1.1 on 2026-09-27 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internship',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='internship',
            name='application_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='application_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='available_seats',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='category',
            field=models.CharField(blank=True, default='Technology', max_length=100),
        ),
        migrations.AddField(
            model_name='internship',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.CharField(blank=True, default='3 Months', max_length=80),
        ),
        migrations.AddField(
            model_name='internship',
            name='eligibility',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='india_payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/india/'),
        ),
        migrations.AddField(
            model_name='internship',
            name='internship_type',
            field=models.CharField(choices=[('remote', 'Remote'), ('onsite', 'On-site'), ('hybrid', 'Hybrid')], default='remote', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='nepal_application_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('99.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='internship',
            name='nepal_payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/nepal/'),
        ),
        migrations.AddField(
            model_name='internship',
            name='payment_instructions',
            field=models.TextField(blank=True, default='Scan the QR code to pay the application fee. Enter the Transaction ID and payment phone number to proceed.'),
        ),
        migrations.AddField(
            model_name='internship',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='published', max_length=20),
        ),
        migrations.AddField(
            model_name='internship',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='internship',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
