# Generated by Django 6.1.1 on 2026-09-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_and_more'),
        ('internships', '0002_alter_internship_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('default_days', models.PositiveIntegerField(default=7, help_text='Suggested project duration in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='internships.internship')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_start_date', models.DateField(blank=True, null=True)),
                ('assigned_deadline', models.DateTimeField(blank=True, null=True)),
                ('duration_days', models.PositiveIntegerField(default=7, help_text='Duration in days assigned by admin')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('github_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('admin_feedback', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='applications.application')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='internships.project')),
            ],
            options={
                'ordering': ['project__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=60)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('github_url', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='internships.projectassignment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('internship', 'order'), name='unique_project_order_per_internship'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('order__gte', 1), ('order__lte', 5)), name='project_order_range_1_to_5'),
        ),
        migrations.AddConstraint(
            model_name='projectassignment',
            constraint=models.UniqueConstraint(fields=('application', 'project'), name='unique_project_assignment_per_application'),
        ),
    ]
