# Generated by Django 6.1.1 on 2026-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('screening', 'Screening'), ('interview', 'Interview'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=32),
        ),
    ]
