# Generated by Django 6.1.1 on 2026-09-28 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_application_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
