"use client";
import { useEffect, useState } from "react";
import { AdminShell } from "@/components/admin/admin-shell";
import { fetchJson } from "@/lib/api";
type Certificate = { id: number; candidate_email: string; candidate_name: string; verification_code: string; issued_date: string; status: string; title: string };
export default function CertificatesPage() {
  const [items, setItems] = useState<Certificate[]>([]); const [error, setError] = useState("");
  useEffect(() => { fetchJson<{ results?: Certificate[] } | Certificate[]>("/admin/certificates/").then((data) => setItems(Array.isArray(data) ? data : data.results || [])).catch(() => setError("Unable to load certificates.")); }, []);
  return <AdminShell><main className="container-shell py-10 md:py-16"><p className="text-xs uppercase tracking-[0.2em] text-blue-600">Credential operations</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-slate-950">Certificates</h1><p className="mt-3 text-slate-500">Manage verifiable candidate certificates.</p>{error && <div className="mt-6 rounded-2xl bg-red-50 p-4 text-sm text-red-700">{error}</div>}<div className="mt-8 overflow-x-auto rounded-[1.8rem] border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-[0.14em] text-slate-500"><tr><th className="px-6 py-4">Certificate</th><th className="px-6 py-4">Candidate</th><th className="px-6 py-4">Issued</th><th className="px-6 py-4">Verification</th><th className="px-6 py-4">Status</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id}><td className="px-6 py-4 font-medium">{item.title}</td><td className="px-6 py-4 text-slate-600">{item.candidate_name}<span className="block text-xs">{item.candidate_email}</span></td><td className="px-6 py-4 text-slate-600">{item.issued_date}</td><td className="px-6 py-4 text-xs"><a className="text-blue-600 hover:underline" href={`/certificates/verify/${item.verification_code}`} target="_blank" rel="noreferrer">{item.verification_code}</a></td><td className="px-6 py-4 capitalize text-slate-600">{item.status}</td></tr>)}</tbody></table>{items.length === 0 && <div className="p-12 text-center text-sm text-slate-500">No certificates found.</div>}</div></main></AdminShell>;
}
