# Generated by Django 6.1.1 on 2026-09-28 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='acceptance_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='candidate_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='offer',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='offer',
            name='duration',
            field=models.CharField(blank=True, default='4 Weeks', max_length=80),
        ),
        migrations.AddField(
            model_name='offer',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='internship_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='offer',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='mode',
            field=models.CharField(blank=True, default='Remote', max_length=30),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_letter_number',
            field=models.CharField(blank=True, max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='revocation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='stipend',
            field=models.CharField(blank=True, default='Unpaid', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='verification_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('sent', 'Sent (Legacy)'), ('declined', 'Declined (Legacy)')], default='draft', max_length=16),
        ),
    ]
