# Generated by Django 6.1.1 on 2026-09-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_country_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/'),
        ),
    ]
