import os
import qrcode
from io import BytesIO
from datetime import date, timedelta

from django.conf import settings
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image as RLImage,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle

PAGE_WIDTH, PAGE_HEIGHT = A4
MARGIN = 36  # 0.5 in / 12.7 mm


def generate_offer_letter_pdf(offer_data, output_file=None):
    """
    Generates a single-page A4 PDF matching the official VINEXTURE Word document design.
    offer_data can be an Offer model instance or a dict with keys:
      - offer_letter_number: str (e.g. 'VIN-OL-2026-000001')
      - verification_code: str (e.g. 'VIN-VRF-...')
      - verification_url: str (optional, defaults to https://www.vinexture.com/offers/verify/<code_or_id>)
      - candidate_name: str
      - candidate_email: str
      - internship_title: str
      - duration: str (e.g. '4 Weeks')
      - mode: str (e.g. 'Remote')
      - start_date: date or str
      - end_date: date or str
      - stipend: str (e.g. 'Unpaid')
      - issue_date: date or str
      - acceptance_deadline: date or str
    """
    # Assets directory
    base_dir = getattr(settings, 'BASE_DIR', os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    assets_dir = os.path.join(base_dir, 'media', 'offer_template_assets')
    os.makedirs(assets_dir, exist_ok=True)

    logo_path = os.path.join(assets_dir, 'image1.png')
    watermark_path = os.path.join(assets_dir, 'watermark_faded.png')
    if not os.path.exists(watermark_path):
        raw_wm = os.path.join(assets_dir, 'image2.png')
        if os.path.exists(raw_wm):
            try:
                from PIL import Image
                im = Image.open(raw_wm).convert('RGBA')
                r, g, b, alpha = im.split()
                faded_alpha = alpha.point(lambda p: int(p * 0.11))
                faded = Image.merge('RGBA', (r, g, b, faded_alpha))
                faded.save(watermark_path, 'PNG')
            except Exception:
                watermark_path = raw_wm

    # Helper function to get values
    def get_val(key, default=''):
        if hasattr(offer_data, key):
            val = getattr(offer_data, key)
            if val is not None:
                if isinstance(val, date):
                    return val.strftime('%d %B %Y')
                return str(val)
        elif isinstance(offer_data, dict) and key in offer_data:
            val = offer_data[key]
            if val is not None:
                if isinstance(val, date):
                    return val.strftime('%d %B %Y')
                return str(val)
        return default

    candidate_name = get_val('candidate_name', 'Candidate Name')
    candidate_email = get_val('candidate_email', 'candidate@vinexture.com')
    internship_title = get_val('internship_title', 'Software Development')
    offer_number = get_val('offer_letter_number', 'VIN-OL-2026-000001')
    verification_code = get_val('verification_code', 'VIN-VRF-0001')
    verification_url = get_val(
        'verification_url',
        f"https://www.vinexture.com/offers/verify/{verification_code}"
    )
    duration = get_val('duration', '4 Weeks')
    mode = get_val('mode', 'Remote')
    start_date = get_val('start_date', '05 October 2026')
    end_date = get_val('end_date', '02 November 2026')
    stipend = get_val('stipend', 'Unpaid')
    issue_date = get_val('issue_date', date.today().strftime('%d %B %Y'))
    acceptance_deadline = get_val('acceptance_deadline', (date.today() + timedelta(days=2)).strftime('%d %B %Y'))

    # Output buffer
    buffer = output_file if output_file else BytesIO()

    # Draw background watermark and footer on the canvas
    def on_page(canvas_obj, doc_obj):
        canvas_obj.saveState()
        # Watermark
        if os.path.exists(watermark_path):
            wm_size = 380
            wm_x = (PAGE_WIDTH - wm_size) / 2
            wm_y = (PAGE_HEIGHT - wm_size) / 2 + 10
            canvas_obj.drawImage(watermark_path, wm_x, wm_y, width=wm_size, height=wm_size, mask='auto')

        # Footer
        footer_text = (
            "This document is digitally generated by VINEXTURE. "
            "Verify its authenticity through the official VINEXTURE verification portal."
        )
        canvas_obj.setFont("Helvetica", 7.5)
        canvas_obj.setFillColor(colors.HexColor('#64748B'))
        canvas_obj.drawCentredString(PAGE_WIDTH / 2, 20, footer_text)
        canvas_obj.restoreState()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=26,
        bottomMargin=30,
    )

    styles = getSampleStyleSheet()

    body_style = ParagraphStyle(
        'OfferBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#0F172A'),
    )

    story = []

    # 1. Header Row (Logo + Brand on Left, Contact info on Right)
    brand_html = (
        '<b><font size="16">VINE</font><font size="16" color="#EE0000">XTURE</font></b><br/>'
        '<font size="7.5" color="#64748B"><b>TECHNOLOGY • DIGITAL SOLUTIONS • TALENT</b></font>'
    )
    brand_p = Paragraph(brand_html, styles['Normal'])

    if os.path.exists(logo_path):
        logo_img = RLImage(logo_path, width=36, height=36)
        logo_tbl = Table([[logo_img, brand_p]], colWidths=[42, 235])
        logo_tbl.setStyle(TableStyle([
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('LEFTPADDING', (0, 0), (-1, -1), 0),
            ('RIGHTPADDING', (0, 0), (-1, -1), 0),
            ('TOPPADDING', (0, 0), (-1, -1), 0),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
        ]))
        brand_cell = logo_tbl
    else:
        brand_cell = brand_p

    contact_html = (
        '<div align="right"><font size="8" color="#475569">'
        'www.vinexture.com &nbsp;&nbsp;|&nbsp;&nbsp; hello@vinexture.com &nbsp;&nbsp;|&nbsp;&nbsp; Global Remote Team'
        '</font></div>'
    )
    contact_p = Paragraph(contact_html, styles['Normal'])

    header_tbl = Table([[brand_cell, contact_p]], colWidths=[265, 258])
    header_tbl.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(header_tbl)
    story.append(Spacer(1, 12))

    # 2. OFFICIAL OFFER LETTER title
    title_p = Paragraph(
        '<div align="center"><b><font size="16" color="#0F172A">OFFICIAL OFFER LETTER</font></b></div>',
        styles['Normal']
    )
    story.append(title_p)
    story.append(Spacer(1, 3))

    # 3. INTERNSHIP PROGRAM subtitle
    sub_title = Paragraph(
        '<div align="center"><font size="9.5" color="#0F172A"><b>I N T E R N S H I P &nbsp;&nbsp;&nbsp; P R O G R A M</b></font></div>',
        styles['Normal']
    )
    story.append(sub_title)
    story.append(Spacer(1, 6))

    # Horizontal divider rule
    divider_tbl = Table([['']], colWidths=[523], rowHeights=[1.5])
    divider_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#CBD5E1')),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(divider_tbl)
    story.append(Spacer(1, 8))

    # 4. Meta & Dynamic QR Code Row
    meta_html = (
        f'<b>Offer Letter No.:</b> {offer_number}<br/>'
        f'<b>Issue Date:</b> {issue_date}'
    )
    meta_p = Paragraph(meta_html, body_style)

    # Generate QR Code
    qr = qrcode.QRCode(box_size=3, border=1)
    qr.add_data(verification_url)
    qr.make(fit=True)
    qr_img = qr.make_image(fill_color='black', back_color='white')
    qr_buf = BytesIO()
    qr_img.save(qr_buf)
    qr_buf.seek(0)
    rl_qr = RLImage(qr_buf, width=60, height=60)

    qr_label = Paragraph(
        '<font size="6.5" color="#64748B"><b>Scan to Verify</b></font>',
        ParagraphStyle('QrLbl', alignment=1)
    )
    qr_box = Table([[rl_qr], [qr_label]], colWidths=[66])
    qr_box.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E1')),
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F8FAFC')),
        ('TOPPADDING', (0, 0), (-1, -1), 2),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))

    meta_tbl = Table([[meta_p, qr_box]], colWidths=[445, 78])
    meta_tbl.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 0),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 8))

    # 5. Candidate Salutation & Opening
    to_p = Paragraph(
        f'<b>To,</b><br/>'
        f'<b>{candidate_name}</b><br/>'
        f'<font color="#475569">{candidate_email}</font>',
        body_style
    )
    story.append(to_p)
    story.append(Spacer(1, 6))

    subj_p = Paragraph(f'<b>Subject: Offer for {internship_title} Internship</b>', body_style)
    story.append(subj_p)
    story.append(Spacer(1, 6))

    dear_p = Paragraph(f'Dear {candidate_name},', body_style)
    p1 = Paragraph(
        f'We are pleased to offer you an internship position as a <b>{internship_title} Intern</b> at <b>VINEXTURE</b>.',
        body_style
    )
    p2 = Paragraph(
        'Based on your application and evaluation, we are offering you the opportunity to join our team and gain practical experience through project-based learning and professional development.',
        body_style
    )
    story.append(dear_p)
    story.append(Spacer(1, 3))
    story.append(p1)
    story.append(Spacer(1, 3))
    story.append(p2)
    story.append(Spacer(1, 8))

    # 6. Internship Details Section
    details_hdr = Paragraph('<u><b>Internship Details</b></u>', body_style)
    story.append(details_hdr)
    story.append(Spacer(1, 3))

    table_data = [
        [Paragraph('<b>Position:</b>', body_style), Paragraph(f'{internship_title} Intern', body_style)],
        [Paragraph('<b>Duration:</b>', body_style), Paragraph(f'{duration}', body_style)],
        [Paragraph('<b>Mode:</b>', body_style), Paragraph(f'{mode}', body_style)],
        [Paragraph('<b>Start Date:</b>', body_style), Paragraph(f'{start_date}', body_style)],
        [Paragraph('<b>End Date:</b>', body_style), Paragraph(f'{end_date}', body_style)],
        [Paragraph('<b>Stipend:</b>', body_style), Paragraph(f'{stipend}', body_style)],
    ]
    details_tbl = Table(table_data, colWidths=[85, 438])
    details_tbl.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 1.5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 1.5),
    ]))
    story.append(details_tbl)
    story.append(Spacer(1, 8))

    # 7. Acceptance Section
    accept_hdr = Paragraph('<b>ACCEPTANCE</b>', body_style)
    p_acc1 = Paragraph('Please confirm your acceptance of this offer through the <b>VINEXTURE Candidate Portal</b>.', body_style)
    p_deadline = Paragraph(f'<b>Offer Acceptance Deadline:</b> {acceptance_deadline}', body_style)
    p_acc2 = Paragraph(
        'By accepting this offer, you acknowledge that you have read and understood the internship terms and agree to comply with the applicable requirements and guidelines.',
        body_style
    )
    p_acc3 = Paragraph('We look forward to having you join VINEXTURE and wish you a successful learning experience.', body_style)

    story.append(accept_hdr)
    story.append(Spacer(1, 3))
    story.append(p_acc1)
    story.append(Spacer(1, 2.5))
    story.append(p_deadline)
    story.append(Spacer(1, 2.5))
    story.append(p_acc2)
    story.append(Spacer(1, 2.5))
    story.append(p_acc3)
    story.append(Spacer(1, 12))

    # 8. Sign-off / Signature Block
    sign_html = (
        '<b>Priya Verma</b><br/>'
        'HR Manager<br/>'
        '<b>VINE<font color="#C00000">XTURE</font></b><br/>'
        '<font size="7.5" color="#64748B">Technology • Digital Solutions • Talent</font>'
    )
    sign_p = Paragraph(sign_html, body_style)
    story.append(sign_p)

    doc.build(story, onFirstPage=on_page)

    if not output_file:
        buffer.seek(0)
        return buffer.getvalue()
    return None
